ALTER TABLE IF EXISTS "CloudExportJobs"
    ADD COLUMN IF NOT EXISTS "AttemptCount" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS "CloudExportJobs"
    ADD COLUMN IF NOT EXISTS "LastAttemptAt" TIMESTAMPTZ NULL;
