namespace Orderly.Core.Models;

public enum ActivityType
{
    CustomerCreated = 0,
    CustomerUpdated = 1,
    DealCreated = 2,
    DealStageChanged = 3,
    FollowUpCreated = 4,
    FollowUpCompleted = 5,
    OrderCreated = 6,
    OrderStatusChanged = 7,
    NoteCreated = 8,
    PriceAdjustmentRequested = 9,
    PriceAdjustmentApproved = 10,
    PriceAdjustmentRejected = 11,
    SyncCompleted = 12,
    FollowUpSnoozed = 13,
    FollowUpCancelled = 14,
    CustomerStatusChanged = 15,
    ConversationMessageAdded = 16,
    AiSuggestionGenerated = 17,
    OcrTaskCreated = 18,
    OcrTaskCompleted = 19,
    OcrTaskFailed = 20,
    AutoReplyDraftPrepared = 21,
    SyncFailed = 22,
    AiSuggestionAccepted = 23,
    AiSuggestionRejected = 24,
    AutoReplySent = 25,
    AutoReplyDraftRejected = 26,
    AutoReplyDraftCopied = 27,
    BackupExported = 28,
    BackupValidationSucceeded = 29,
    BackupValidationFailed = 30
}
