using CommunityToolkit.Mvvm.ComponentModel;

namespace Orderly.App.ViewModels;

public partial class MainViewModel
{
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(IsStatusError))]
    [NotifyPropertyChangedFor(nameof(StatusMessageTitle))]
    [NotifyPropertyChangedFor(nameof(CustomersEmptyStateText))]
    [NotifyPropertyChangedFor(nameof(OrdersEmptyStateText))]
    private string statusMessage = "准备就绪";

    [ObservableProperty]
    [NotifyCanExecuteChangedFor(nameof(AddConversationMessageCommand))]
    [NotifyCanExecuteChangedFor(nameof(SelectOcrImageCommand))]
    [NotifyCanExecuteChangedFor(nameof(ConvertOcrToConversationMessageCommand))]
    private string conversationMessageInput = string.Empty;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(IsBusy))]
    [NotifyCanExecuteChangedFor(nameof(RefreshCommand))]
    [NotifyCanExecuteChangedFor(nameof(SelectBackupFileCommand))]
    [NotifyCanExecuteChangedFor(nameof(ExportBackupCommand))]
    [NotifyCanExecuteChangedFor(nameof(ValidateBackupCommand))]
    [NotifyCanExecuteChangedFor(nameof(RestoreBackupCommand))]
    [NotifyCanExecuteChangedFor(nameof(PreviewCloudImportCommand))]
    [NotifyCanExecuteChangedFor(nameof(CommitCloudImportCommand))]
    [NotifyCanExecuteChangedFor(nameof(AddNoteCommand))]
    [NotifyCanExecuteChangedFor(nameof(AddFollowUpCommand))]
    [NotifyCanExecuteChangedFor(nameof(AddCustomerCommand))]
    [NotifyCanExecuteChangedFor(nameof(AddOrderCommand))]
    [NotifyCanExecuteChangedFor(nameof(AddConversationMessageCommand))]
    [NotifyCanExecuteChangedFor(nameof(SelectOcrImageCommand))]
    [NotifyCanExecuteChangedFor(nameof(ConvertOcrToConversationMessageCommand))]
    [NotifyCanExecuteChangedFor(nameof(AddPriceAdjustmentCommand))]
    [NotifyCanExecuteChangedFor(nameof(ChangeDealStageCommand))]
    [NotifyCanExecuteChangedFor(nameof(AdvanceDealStageCommand))]
    [NotifyCanExecuteChangedFor(nameof(ChangeCustomerStatusCommand))]
    [NotifyCanExecuteChangedFor(nameof(ChangeOrderStatusCommand))]
    [NotifyCanExecuteChangedFor(nameof(CompleteFollowUpCommand))]
    [NotifyCanExecuteChangedFor(nameof(SnoozeFollowUpCommand))]
    [NotifyCanExecuteChangedFor(nameof(CancelFollowUpCommand))]
    [NotifyCanExecuteChangedFor(nameof(GenerateAiSuggestionCommand))]
    [NotifyCanExecuteChangedFor(nameof(AcceptAiSuggestionCommand))]
    [NotifyCanExecuteChangedFor(nameof(RejectAiSuggestionCommand))]
    [NotifyCanExecuteChangedFor(nameof(PrepareAutoReplyDraftCommand))]
    [NotifyCanExecuteChangedFor(nameof(CopyAutoReplyDraftCommand))]
    [NotifyCanExecuteChangedFor(nameof(MarkAutoReplySentCommand))]
    [NotifyCanExecuteChangedFor(nameof(RejectAutoReplyDraftCommand))]
    [NotifyCanExecuteChangedFor(nameof(RefreshWorkbenchTasksCommand))]
    [NotifyCanExecuteChangedFor(nameof(OpenWorkbenchTaskCommand))]
    [NotifyCanExecuteChangedFor(nameof(RunSearchCommand))]
    [NotifyCanExecuteChangedFor(nameof(RefreshSearchCommand))]
    [NotifyCanExecuteChangedFor(nameof(OpenSearchResultCommand))]
    private bool isLoading;

    [ObservableProperty]
    private string? loadError;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(IsBusy))]
    [NotifyCanExecuteChangedFor(nameof(RefreshCommand))]
    [NotifyCanExecuteChangedFor(nameof(SelectBackupFileCommand))]
    [NotifyCanExecuteChangedFor(nameof(ExportBackupCommand))]
    [NotifyCanExecuteChangedFor(nameof(ValidateBackupCommand))]
    [NotifyCanExecuteChangedFor(nameof(RestoreBackupCommand))]
    [NotifyCanExecuteChangedFor(nameof(PreviewCloudImportCommand))]
    [NotifyCanExecuteChangedFor(nameof(CommitCloudImportCommand))]
    [NotifyCanExecuteChangedFor(nameof(AddNoteCommand))]
    [NotifyCanExecuteChangedFor(nameof(AddFollowUpCommand))]
    [NotifyCanExecuteChangedFor(nameof(AddCustomerCommand))]
    [NotifyCanExecuteChangedFor(nameof(AddOrderCommand))]
    [NotifyCanExecuteChangedFor(nameof(AddConversationMessageCommand))]
    [NotifyCanExecuteChangedFor(nameof(SelectOcrImageCommand))]
    [NotifyCanExecuteChangedFor(nameof(ConvertOcrToConversationMessageCommand))]
    [NotifyCanExecuteChangedFor(nameof(AddPriceAdjustmentCommand))]
    [NotifyCanExecuteChangedFor(nameof(ChangeDealStageCommand))]
    [NotifyCanExecuteChangedFor(nameof(AdvanceDealStageCommand))]
    [NotifyCanExecuteChangedFor(nameof(ChangeCustomerStatusCommand))]
    [NotifyCanExecuteChangedFor(nameof(ChangeOrderStatusCommand))]
    [NotifyCanExecuteChangedFor(nameof(CompleteFollowUpCommand))]
    [NotifyCanExecuteChangedFor(nameof(SnoozeFollowUpCommand))]
    [NotifyCanExecuteChangedFor(nameof(CancelFollowUpCommand))]
    [NotifyCanExecuteChangedFor(nameof(GenerateAiSuggestionCommand))]
    [NotifyCanExecuteChangedFor(nameof(AcceptAiSuggestionCommand))]
    [NotifyCanExecuteChangedFor(nameof(RejectAiSuggestionCommand))]
    [NotifyCanExecuteChangedFor(nameof(PrepareAutoReplyDraftCommand))]
    [NotifyCanExecuteChangedFor(nameof(CopyAutoReplyDraftCommand))]
    [NotifyCanExecuteChangedFor(nameof(MarkAutoReplySentCommand))]
    [NotifyCanExecuteChangedFor(nameof(RejectAutoReplyDraftCommand))]
    [NotifyCanExecuteChangedFor(nameof(RefreshWorkbenchTasksCommand))]
    [NotifyCanExecuteChangedFor(nameof(OpenWorkbenchTaskCommand))]
    [NotifyCanExecuteChangedFor(nameof(RunSearchCommand))]
    [NotifyCanExecuteChangedFor(nameof(RefreshSearchCommand))]
    [NotifyCanExecuteChangedFor(nameof(OpenSearchResultCommand))]
    private bool isSaving;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(IsBusy))]
    [NotifyCanExecuteChangedFor(nameof(RefreshCommand))]
    [NotifyCanExecuteChangedFor(nameof(SelectBackupFileCommand))]
    [NotifyCanExecuteChangedFor(nameof(ExportBackupCommand))]
    [NotifyCanExecuteChangedFor(nameof(ValidateBackupCommand))]
    [NotifyCanExecuteChangedFor(nameof(RestoreBackupCommand))]
    [NotifyCanExecuteChangedFor(nameof(PreviewCloudImportCommand))]
    [NotifyCanExecuteChangedFor(nameof(CommitCloudImportCommand))]
    [NotifyCanExecuteChangedFor(nameof(AddNoteCommand))]
    [NotifyCanExecuteChangedFor(nameof(AddFollowUpCommand))]
    [NotifyCanExecuteChangedFor(nameof(AddCustomerCommand))]
    [NotifyCanExecuteChangedFor(nameof(AddOrderCommand))]
    [NotifyCanExecuteChangedFor(nameof(AddConversationMessageCommand))]
    [NotifyCanExecuteChangedFor(nameof(SelectOcrImageCommand))]
    [NotifyCanExecuteChangedFor(nameof(ConvertOcrToConversationMessageCommand))]
    [NotifyCanExecuteChangedFor(nameof(AddPriceAdjustmentCommand))]
    [NotifyCanExecuteChangedFor(nameof(ChangeDealStageCommand))]
    [NotifyCanExecuteChangedFor(nameof(AdvanceDealStageCommand))]
    [NotifyCanExecuteChangedFor(nameof(ChangeCustomerStatusCommand))]
    [NotifyCanExecuteChangedFor(nameof(ChangeOrderStatusCommand))]
    [NotifyCanExecuteChangedFor(nameof(CompleteFollowUpCommand))]
    [NotifyCanExecuteChangedFor(nameof(SnoozeFollowUpCommand))]
    [NotifyCanExecuteChangedFor(nameof(CancelFollowUpCommand))]
    [NotifyCanExecuteChangedFor(nameof(GenerateAiSuggestionCommand))]
    [NotifyCanExecuteChangedFor(nameof(AcceptAiSuggestionCommand))]
    [NotifyCanExecuteChangedFor(nameof(RejectAiSuggestionCommand))]
    [NotifyCanExecuteChangedFor(nameof(PrepareAutoReplyDraftCommand))]
    [NotifyCanExecuteChangedFor(nameof(CopyAutoReplyDraftCommand))]
    [NotifyCanExecuteChangedFor(nameof(MarkAutoReplySentCommand))]
    [NotifyCanExecuteChangedFor(nameof(RejectAutoReplyDraftCommand))]
    [NotifyCanExecuteChangedFor(nameof(RefreshWorkbenchTasksCommand))]
    [NotifyCanExecuteChangedFor(nameof(OpenWorkbenchTaskCommand))]
    [NotifyCanExecuteChangedFor(nameof(RunSearchCommand))]
    [NotifyCanExecuteChangedFor(nameof(RefreshSearchCommand))]
    [NotifyCanExecuteChangedFor(nameof(OpenSearchResultCommand))]
    private bool isGeneratingAiSuggestion;

    private bool _isSynchronizingSelection;
    private int _detailLoadVersion;
}
